### ISSUE TITLE
Re-implementer deltakerbrukere

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMusers#10]
Administrering av deltakerbrukere må re-implementeres

Gammel modul lagde en passordliste - denne skal nå fjernes, og brukerne må heller forholde seg til glemt passord-funksjonen. Dette bør gjøre det litt lettere (forhåpentligvis).

Er det en idé å lagre delta_user_id som metadata på brukerobjektet, heller enn i en egen tabell? Eller gjør det ting verre?

**Comment by AsgeirSH** [comment]
Vi lagrer allerede delta_user_id på bruker-iden i smartukm_participant, men ikke funnet noe å bruke den til. Er det heller en idè å implementere Delta-innlogging til WP? Så er det faktisk èn bruker å forholde seg til, de får facebook-innlogging etc.

**Comment by mariusmandal** [comment]
Liker tanken @AsgeirSH , men finner ikke det feltet. Har foreslått en løsning i UKMNorge/UKMdelta#234 - kan du se på den?

**Comment by mariusmandal** [comment]
**På grunn av UKMNorge/UKMdelta#234** 
- må lagring av bruker-ID gjøres i en egen tabell `delta_wp_user`
- må deltakerbrukere ikke automatisk legge til brukerne på sin egen blogg, slik det var gjort tidligere

**På grunn av UKMNorge/UKMbilder#11**
Må deltakerbrukere opprette wordpress-bruker (og sette inn rad i `delta_wp_user`) for alle `arrangør`- og `media`-innslag til sitt arrangement. Dette gjør det mulig å merke bildene med riktig fotograf.

**Relasjoner**
- Delta UID finnes via person-objektet til påmeldt `arrangør`- og `media`-innslag. ( `$innslag->getPersoner()->getSingle()`)
- `UKMNorge\Innslag\Personer\Person->getId()` == `deltaDB.ukm_user::pameld_user`

[UKMapi\Database\SQL\Query](https://github.com/UKMNorge/UKMapi/blob/master/Database/SQL/Query.php#L31) tar inn `'ukmdelta'` som tredje parameter for å spørre delta-databasen.

Fordi noen innslag kan være påmeldt av admin (og dermed ha en rad i `ss3DB.smartukm_participant`, men ikke i `deltaDB.ukm_user`), må `delta_wp_user` også ha feltet `PID`

**Comment by AsgeirSH** [comment]
Skriver èn komponent (controller) uten noe GUI-funksjonalitet for å opprette nye deltakerbrukere og linke de mot delta_wp_user. Kan inkluderes i UKMbilder etc for å automatisk opprette fotografbrukere. Denne bruker navn fra smartukm_participant, som vil si at vi slipper at brukerne må fikse navnet sitt selv (i dag: navn.navnesen1 som journalist, f.eks).

Skriver en annen komponent _med_ GUI for å administrere opprettede brukere, og eskalere / de-eskalere de.

**Comment by mariusmandal** [comment]
Hva er status på denne @AsgeirSH ? :)

**Comment by AsgeirSH** [comment]
Mangler funksjonalitet på opp/nedgrader-knappene, ellers klar 😄

**Comment by AsgeirSH** [comment]
Lukker denne nå som du har fått den ut :)
