### ISSUE TITLE
Nye deltakerbrukere må også ha en rolle hos hovedbloggen for å få opp Brukerstøtte-panelet

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMusers#11]

**Comment by mariusmandal** [comment]
Selve rollen de skal ha er `subscriber`, btw

**Comment by AsgeirSH** [comment]
Markedsførings-plugin har for øyeblikket subscriber som required rolle. Den er deaktivert for øyeblikket, så ikke krise, men bør sjekkes før den kobles inn igjen.
