### ISSUE TITLE
Brukere får feilaktig feilbeskjed

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMusers#14]
Brukere som har tilgang til hovedbloggen får denne (som de da ikke skal ha..)
```
På grunn av en feil, vil ikke brukeren kunne åpne 'Brukerstøtte'-siden. Kontakt support@ukm.no for hjelp.
```

**Comment by mariusmandal** [comment]
Testet på Kongsberg. Får alltid feilmelding :(

**Comment by mariusmandal** [comment]
Kan du se på denne @AsgeirSH ? :)

**Comment by AsgeirSH** [comment]
Får ikke sett på det før senere @mariusmandal, men tror feilen er rundt her et sted:

https://github.com/UKMNorge/UKMusers/commit/54fa9fcd7a091b92e028388677a7083e56409516#diff-fd7a2822f97a9e24642bade4723d17a7R188

Funksjonskallet skal includere `subscriber` - men siden det ikke brukes skal `harHovedbloggBruker()` returnere true så lenge brukeren faktisk er koblet til hovedbloggen. Du har sjekka at brukeren faktisk blir koblet opp?

**Comment by mariusmandal** [comment]
Per i dag ser det ut til at denne fungerer akkurat som den skal. Kan det være at vi har gjort endringer et sted som fikset problemet? Pull til server som manglet? Idk. Nå funker det i alle fall 100% både i dev og prod (både Kongsberg, Trondheim og Asker). 
Kaller det fikset til vi får nye bevis på at det er en bug
