### ISSUE TITLE
Brukernavn eksisterer

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMusers#3]
Funksjonen håndterer ikke eksisterende brukere riktig

**Comment by mariusmandal** [comment]
@AsgeirSH sier: Sjekk for SQL-error, mulig den feiler på å sette inn raden. Unique-constraint på e-post, muligens

**Comment by mariusmandal** [comment]
Kanskje det er det som er feilen? Den finner ut at brukernavnet eksisterer, genererer nytt brukernavn (med tall-suffix) og forsøker å inserte, men feiler på e-post-constraint?

**Comment by AsgeirSH** [comment]
Til neste gang noe sånt dukker opp:
Den finner ut at brukernavnet eksisterer, genererer nytt brukernavn, forsøker å inserte, men feiler på e-post.

Problemet er at brukere kan ha forskjellig p_id fra år til år. (Eksempel: Oda Karoline Sørøy, 
![image](https://cloud.githubusercontent.com/assets/1831028/12484090/d444942a-c058-11e5-9727-7a101d9289da.png)
Oppdater UKMusers.class til å sjekke om fornavn, etternavn og e-post-adresse til en bruker er likt med gjeldende bruker, og oppdaterer p_id i ukm_wp_deltakere til den nyeste p_id.

**Comment by mariusmandal** [comment]
Jeg er ikke sikker, og har ikke fått testet, men vil ikke i utgangspunktet dette kunne løse problemet?

```
public function wp_username_is_mine() {
    $wp_user_id = $this->wp_username_exists( $this->username );

    if( $wp_user_id ) {
        $wp_user_participant_id = get_user_meta( $wp_user_id, 'p_id', true );
        if( $wp_user_participant_id == $this->p_id ) {
            return true;
        }

        $sql = new SQL("SELECT `p_id` FROM `smartukm_participant`
                        WHERE `p_firstname` = '#firstname'
                        AND `p_lastname` = '#lastname'
                        AND `p_email` = '#email'
                        ORDER BY `p_id` DESC",
                        array(  'firstname' => $this->deltakerObject->get('p_firstname'),
                                'lastname' => $this->deltakerObject->get('p_lastname'),
                                'email' => $this->deltakerObject->get('p_email'));
        $res = $sql->run();
        if( $res ) {
            while( $r = mysql_fetch_assoc( $res ) ) {
                if( $r['p_id'] == $wp_user_participant_id ) {
                    $this->_wp_set_new_p_id( $this->p_id );
                    return true;
                }
            }
        }
    }
    return false;
}
```

Og så legge til følgende i konstruktøren:

```
    $this->deltakerObject = $deltakerObject;
```

Og skrive følgende funksjon

```
public function _wp_set_new_p_id( $new_p_id ){
    // ASGEIR-CODE GOES HERE
    throw new Exception('Code missing in line '. __LINE__ );
}
```

**Comment by AsgeirSH** [comment]
Ikke helt, tror jeg. Jeg gjorde mye av det samme, men har skrevet en del kode etter vi pratet tidligere. 

Sendt fra min iPad

**Comment by AsgeirSH** [comment]
Fixed by rewrite!
